// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/GophKeeper/server/internal/app/user (interfaces: IUserStore)

// Package mock_user is a generated GoMock package.
package mocks

import (
        context "context"
        reflect "reflect"

        user "github.com/GophKeeper/server/internal/app/user"
        gomock "github.com/golang/mock/gomock"
)

// MockIUserStore is a mock of IUserStore interface.
type MockIUserStore struct {
        ctrl     *gomock.Controller
        recorder *MockIUserStoreMockRecorder
}

// MockIUserStoreMockRecorder is the mock recorder for MockIUserStore.
type MockIUserStoreMockRecorder struct {
        mock *MockIUserStore
}

// NewMockIUserStore creates a new mock instance.
func NewMockIUserStore(ctrl *gomock.Controller) *MockIUserStore {
        mock := &MockIUserStore{ctrl: ctrl}
        mock.recorder = &MockIUserStoreMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserStore) EXPECT() *MockIUserStoreMockRecorder {
        return m.recorder
}

// Create mocks base method.
func (m *MockIUserStore) Create(arg0 context.Context, arg1 user.User) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Create", arg0, arg1)
        ret0, _ := ret[0].(error)
        return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUserStoreMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserStore)(nil).Create), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockIUserStore) GetUser(arg0 context.Context, arg1 string) (*user.User, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
        ret0, _ := ret[0].(*user.User)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUserStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUserStore)(nil).GetUser), arg0, arg1)
}